# Generated by Django 4.2.10 on 2024-04-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_middle_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='name',
            new_name='card_num',
        ),
    ]
