# Generated by Django 4.2.10 on 2024-04-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='CVV',
            field=models.CharField(default='000', max_length=3, verbose_name='CVV'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='date',
            field=models.CharField(default='00.00.00', max_length=8, verbose_name='Срок годности'),
        ),
    ]
