# Generated by Django 4.2.10 on 2024-04-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_paymentmethod_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='primary_payment_method',
        ),
        migrations.RemoveField(
            model_name='user',
            name='secondary_payment_method',
        ),
    ]
