# Generated by Django 4.2.10 on 2024-03-29 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='slig',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='slig',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='Пароль'),
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='user',
            name='primary_payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_payment_method_for_user', to='goods.paymentmethod', verbose_name='Основной способ оплаты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='secondary_payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_payment_method_for_user', to='goods.paymentmethod', verbose_name='Дополнительный способ оплаты'),
        ),
    ]
