# Generated by Django 4.2.10 on 2024-04-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discripton',
            new_name='description',
        ),
        migrations.AddField(
            model_name='discount',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Итоговая цена'),
        ),
    ]
