# Generated by Django 4.2.10 on 2024-04-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specification',
            options={'verbose_name': 'Спецификации', 'verbose_name_plural': 'Спецификация'},
        ),
        migrations.AlterModelTable(
            name='specification',
            table='specification',
        ),
    ]
