# Generated by Django 4.2.10 on 2024-04-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_subscriptions_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='peculiarities',
            field=models.TextField(blank=True, null=True, verbose_name='Особенности'),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, null=True, verbose_name='Технические характеристики'),
        ),
    ]
