# Generated by Django 4.2.10 on 2024-04-11 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_product_peculiarities_product_specifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип носителя')),
                ('delivery_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип поставки')),
                ('purpose', models.CharField(blank=True, max_length=100, null=True, verbose_name='Назначение')),
                ('validity_period', models.CharField(blank=True, max_length=100, null=True, verbose_name='Срок действия')),
                ('bitness', models.CharField(blank=True, max_length=20, null=True, verbose_name='Разрядность')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.license', verbose_name='Технические характеристики'),
        ),
    ]
