# Generated by Django 4.2.10 on 2024-04-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_product_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.FloatField(default=0.0, verbose_name='Средний рейтинг'),
        ),
    ]
