# Generated by Django 4.2.10 on 2024-04-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_product_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='bitness',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Разрядность'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип поставки'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Процент скидки'),
        ),
        migrations.AddField(
            model_name='product',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Итоговая цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='media_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип носителя'),
        ),
        migrations.AddField(
            model_name='product',
            name='purpose',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Назначение'),
        ),
        migrations.AddField(
            model_name='product',
            name='validity_period',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Срок действия'),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Specification',
        ),
    ]
