# Generated by Django 4.2.10 on 2024-04-23 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_remove_specification_product_product_bitness_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='final_price',
        ),
    ]
