# Generated by Django 4.2.10 on 2024-04-23 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_remove_product_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='validity_period',
        ),
    ]
