# Generated by Django 4.2.10 on 2024-04-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_alter_product_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_added',
            field=models.DateField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
