# Generated by Django 4.2.10 on 2024-04-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_alter_review_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.CharField(blank=True, default='Да', max_length=3, null=True, verbose_name='Наличие товара'),
        ),
    ]
