# Generated by Django 4.2.10 on 2024-04-28 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0013_favoriteproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteproduct',
            options={'verbose_name': 'Избранный продукт', 'verbose_name_plural': 'Избранные продукты'},
        ),
        migrations.AlterUniqueTogether(
            name='favoriteproduct',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='favoriteproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.product', verbose_name='Избранный продукт'),
        ),
        migrations.AlterField(
            model_name='favoriteproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
