# Generated by Django 4.2.10 on 2024-05-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_alter_favoriteproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
