# Generated by Django 4.2.10 on 2024-05-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0015_alter_review_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popularity',
            field=models.IntegerField(default=0, verbose_name='Популярность'),
        ),
    ]
