# Generated by Django 4.2.10 on 2024-05-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_product_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='popularity',
            field=models.IntegerField(default=0, verbose_name='Количество покупок'),
        ),
    ]
