# Generated by Django 4.2.10 on 2024-04-17 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='client',
            new_name='user',
        ),
    ]
